---
title: "Pedal Force Asymmetry — Efficiency & Force Effectiveness Analysis"
format: html
editor: visual
execute:
  message: false
  warning: false
---

## Loading libraries

```{r librairies}

#| include: false


library(tidyverse)
library(ggplot2)
library(forcats)
library(knitr)
library(broom) #lm model
library(broom.mixed)
library(emmeans) 
library(ggpubr)
library(RColorBrewer)
library(patchwork)

#stats
library(nlme)
library(ggeffects)
library(lme4)
library(lmerTest)
library(car)
library(DHARMa)
library(influence.ME)
library(mgcv)
library(performance)
library(gridExtra)

```

## Loading data

```{r load-data}

sub01 <- read.delim(file = "data/sub1_data_join_cond.csv", sep=",") |> mutate(subject="sub01")|>mutate(BM=69.3,Pow_norm=Tot_power/BM, DOM="Right")

sub02 <- read.delim(file = "data/sub2_data_join_cond.csv", sep=",") |> mutate(subject="sub02")|>mutate(BM=70.1,Pow_norm=Tot_power/BM, DOM="Left")

sub03 <- read.delim(file = "data/sub3_data_join_cond.csv", sep=",") |> mutate(subject="sub03")|>mutate(BM=58.2,Pow_norm=Tot_power/BM, DOM=ifelse(row_number() <= 5, "Left", "Right"))

sub06 <- read.delim(file = "data/sub6_data_join_cond.csv", sep=",") |> mutate(subject="sub06") |>mutate(BM=88.8,Pow_norm=Tot_power/BM, DOM="Right")

sub07 <- read.delim(file = "data/sub7_data_join_cond.csv", sep=",") |> mutate(subject="sub07") |>mutate(BM=71.9,Pow_norm=Tot_power/BM, DOM="Right")

sub08 <- read.delim(file = "data/sub8_data_join_cond.csv", sep=",") |> mutate(subject="sub08") |>mutate(BM=67.8,Pow_norm=Tot_power/BM, DOM="Left")

sub09 <- read.delim(file = "data/sub9_data_join_cond.csv", sep=",") |> mutate(subject="sub09")|>mutate(BM=58.6,Pow_norm=Tot_power/BM, DOM="Left")

sub10 <- read.delim(file = "data/sub10_data_join_cond.csv", sep=",") |> mutate(subject="sub10")|>mutate(BM=71.2,Pow_norm=Tot_power/BM, DOM="Left")

sub11 <- read.delim(file = "data/sub11_data_join_cond.csv", sep=",") |> mutate(subject="sub11")|>mutate(BM=80.8,Pow_norm=Tot_power/BM, DOM="Left")

sub12 <- read.delim(file = "data/sub12_data_join_cond.csv", sep=",") |> mutate(subject="sub12") |>mutate(BM=71,Pow_norm=Tot_power/BM, DOM="Right")

sub13 <- read.delim(file = "data/sub13_data_join_cond.csv", sep=",") |> mutate(subject="sub13") |>mutate(BM=72.7,Pow_norm=Tot_power/BM, DOM="Left")

sub14 <- read.delim(file = "data/sub14_data_join_cond.csv", sep=",") |> mutate(subject="sub14")|>mutate(BM=58,Pow_norm=Tot_power/BM, DOM=ifelse(row_number() <= 5, "Right", "Left"))  # FB PAS BCP RESPECTE A 2.5

sub15 <- read.delim(file = "data/sub15_data_join_cond.csv", sep=",") |> mutate(subject="sub15")|>mutate(BM=75.5,Pow_norm=Tot_power/BM, DOM="Left")

sub16 <- read.delim(file = "data/sub16_data_join_cond.csv", sep=",") |> mutate(subject="sub16") |>mutate(BM=72.2,Pow_norm=Tot_power/BM, DOM="Right")

sub17 <- read.delim(file = "data/sub17_data_join_cond.csv", sep=",") |> mutate(subject="sub17") |>mutate(BM=61.4,Pow_norm=Tot_power/BM, DOM="Left")



```

## Combine & prepare data

```{r prepare-data}

# Combine the subjects' data and remove the no-feedback condition

all_data <- rbind(sub01,sub02,sub03,sub06,sub07,sub08,sub09,sub10,sub11,sub12,sub13,sub14,sub15,sub16,sub17)  |>filter(percents!="No") 


# Use absolute value of the symmetry index
all_data$SI_force <- abs(all_data$SI_force)

# Split by power condition
all_data_1p5 <- all_data |> filter(pow_condition == "1p5")
all_data_2p5 <- all_data |> filter(pow_condition == "2p5")

# Reshape to long format for plotting
all_data_long <- all_data |>
  pivot_longer(
    cols      = c(efficiency, FE),
    names_to  = "variable",
    values_to = "value"
  )

```

## Descriptive statistics

```{r descriptive-stats}

# 1.5 W/kg
tab_1p5 <- all_data |>
  filter(pow_condition == "1p5") |>
  group_by(percents) |>
  summarise(
    cad_mean      = mean(Cadence),
    cad_sd        = sd(Cadence),
    mean_1p5      = mean(Pow_norm),
    sd_1p5        = sd(Pow_norm),
    Si_force_mean = mean(SI_force),
    sd_SI         = sd(SI_force)
  )

# 2.5 W/kg
tab_2p5 <- all_data |>
  filter(pow_condition == "2p5") |>
  group_by(percents) |>
  summarise(
    cad_mean      = mean(Cadence),
    cad_sd        = sd(Cadence),
    mean_2p5      = mean(Pow_norm),
    sd_2p5        = sd(Pow_norm),
    Si_force_mean = mean(SI_force),
    sd_SI         = sd(SI_force)
  )

# Dominant vs non-dominant force
all_data_DOM_UNDOM <- all_data |>
  group_by(subject) |>
  mutate(
    Force_DOM   = ifelse(DOM == "Right", RF_norm, LF_norm),
    Force_UNDOM = ifelse(DOM == "Right", LF_norm, RF_norm)
  )

all_data_DOM_UNDOM_1p5 <- all_data_DOM_UNDOM |>
  filter(pow_condition == "1p5") |>
  group_by(percents) |>
  summarise(
    DOM_mean   = mean(Force_DOM),
    DOM_sd     = sd(Force_DOM),
    UNDOM_mean = mean(Force_UNDOM),
    UNDOM_sd   = sd(Force_UNDOM)
  )

all_data_DOM_UNDOM_2p5 <- all_data_DOM_UNDOM |>
  filter(pow_condition == "2p5") |>
  group_by(percents) |>
  summarise(
    DOM_mean   = mean(Force_DOM),
    DOM_sd     = sd(Force_DOM),
    UNDOM_mean = mean(Force_UNDOM),
    UNDOM_sd   = sd(Force_UNDOM)
  )

```

## Linear mixed models — Efficiency

```{r LMM-efficiency}

# With interaction
mod_eff <- lmer(efficiency ~ SI_force * pow_condition + (1 | subject), data = all_data)
summary(mod_eff)

# With interaction with asymmetry as a categorical variable
mod_eff_cate_inter <- lmer(efficiency ~ percents * pow_condition + (1 | subject), data = all_data)
summary(mod_eff_cate_inter)

# Without interaction (no significant interaction found)
mod_eff1 <- lmer(efficiency ~ SI_force + pow_condition + (1 | subject), data = all_data)
summary(mod_eff1)

# SI_force as categorical variable
mod_eff_cate <- lmer(efficiency ~ percents + pow_condition + (1 | subject), data = all_data)
summary(mod_eff_cate)


```

## Linear mixed models — Force effectiveness

```{r LMM-FE}


# With interaction
mod_FE <- lmer(FE ~ SI_force * pow_condition + (1 | subject), data = all_data)
summary(mod_FE)


# With interaction with asymmetry as a categorical variable
mod_FE_cate_inter <- lmer(FE ~ percents * pow_condition + (1 | subject), data = all_data)
summary(mod_FE_cate_inter)


# Without interaction (no significant interaction found)
mod_FE1 <- lmer(FE ~ SI_force + pow_condition + (1 | subject), data = all_data)
summary(mod_FE1)


# SI_force as categorical variable
mod_FE_cate <- lmer(FE ~ percents + pow_condition + (1 | subject), data = all_data)
summary(mod_FE_cate)
```

## Model predictions for plots

```{r stats}

# Efficiency
pred_eff <- ggpredict(mod_eff1,terms = c("SI_force", "pow_condition"))
pred_eff$variable <- "efficiency"

pred_eff <- pred_eff |> 
  rename(pow_condition = group)

# Force effectiveness
pred_FE <- ggpredict(mod_FE1,terms = c("SI_force", "pow_condition"))
pred_FE$variable <- "efficiency"

pred_FE <- pred_FE |> 
  rename(pow_condition = group)
```

## Graphs — Scatter plots (SI_force)

```{r graphs-SI_force}

# Efficiency

p3 <- ggplot(
  all_data_long |> filter(variable == "efficiency"),
  aes(x = SI_force, y = value)
) +
  
  geom_point(
    aes(
      color = percents,
      shape = pow_condition,
      size = pow_condition
    )
  ) +
  
  geom_line(
    data = pred_eff,
    aes(
      x = x,
      y = predicted,
      linetype = pow_condition
    ),
    color = "black",
    linewidth = 0.8
  ) +
  
  scale_color_manual(
    name = "PFA Target",
    values = c(
      "0%"  = "#E69F00",
      "10%" = "#56B4E9",
      "20%" = "#009E73",
      "30%" = "#6A3D9A"
    )
  ) +
  
  scale_shape_manual(
    name = "Average MPO",
    values = c(
      "1p5" = 16,
      "2p5" = 18
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  scale_size_manual(
    values = c(
      "1p5" = 2.2,
      "2p5" = 3
    )
  ) +
  
  scale_linetype_manual(
    name = "Average MPO",
    values = c(
      "1p5" = "solid",
      "2p5" = "dotdash"
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  guides(
    color = guide_legend(
      nrow = 2,
      byrow = TRUE,
      override.aes = list(size = 3)
    ),
    
    shape = guide_legend(
      nrow = 1,
      override.aes = list(size = c(2.5, 3))
    ),
    
    size = "none"
  ) +
  
  scale_x_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  labs(
    x = "Pedal Force Asymmetry (%)",
    y = "Net Efficiency (%)"
  ) +
  
  theme_classic(base_size = 8) +
  
  theme(
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    ),
    
    legend.position = "top",
    legend.box = "vertical",
    
    legend.spacing.y = unit(0, "mm"),
    legend.spacing.x = unit(1, "mm"),
    
    legend.key.width = unit(8, "mm"),
    legend.key.height = unit(4, "mm"),
    
    plot.margin = margin(
      1, 1, 1, 1,
      unit = "mm"
    )
  )

p3

# Force effectiveness

p4 <- ggplot(all_data_long |> filter(variable == "FE")) +
  aes(x = SI_force, y = value) +
  
  geom_point(
    aes(color = percents,
        shape = pow_condition,
        size = pow_condition)
  ) +
  
  geom_line(
    data = pred_FE,
    aes(x = x,
        y = predicted,
        linetype = pow_condition),
    color = "black",
    linewidth = 0.9
  ) +
  
  scale_color_manual(
    name = "PFA Target",
    values = c(
      "0%"  = "#E69F00",
      "10%" = "#56B4E9",
      "20%" = "#009E73",
      "30%" = "#6A3D9A"
    )
  ) +
  
  scale_shape_manual(
    name = "Average MPO",
    values = c(
      "1p5" = 16,
      "2p5" = 18
    ),
    labels = c("1.5 W/kg", "2.5 W/kg")
  ) +
  
  scale_size_manual(
    values = c(
      "1p5" = 2.2,
      "2p5" = 3
    )
  ) +
  
  scale_linetype_manual(
    name = "Average MPO",
    values = c(
      "1p5" = "solid",
      "2p5" = "dotdash"
    ),
    labels = c("1.5 W/kg", "2.5 W/kg")
  ) +
  guides(
    color = guide_legend(
      nrow = 2,
      byrow = TRUE,
      override.aes = list(size = 3)
    ),
    
    shape = guide_legend(
      nrow = 1,
      override.aes = list(size = c(2.5, 3))
    ),
    
    size = "none"
  ) +
  
  scale_x_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  labs(
    x = "Pedal Force Asymmetry (%)",
    y = "FE (%)"
  ) +
  
  theme_classic(base_size = 8) +
  
  theme(
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    ),
    
    legend.position = "top",
    legend.box = "vertical",
    
    legend.spacing.y = unit(0, "mm"),
    legend.spacing.x = unit(1, "mm"),
    
    legend.key.width = unit(8, "mm"),
    legend.key.height = unit(4, "mm"),
    
    plot.margin = margin(
      1, 1, 1, 1,
      unit = "mm"
    ))

p4

ggsave("efficiency_final.png",p3,width = 84,height = 84,units = "mm")

ggsave("FE_final.png",p4,width = 84,height = 84,units = "mm", dpi=300)
```

## Graphs — Box plots

```{r box_plots}

# Efficiency

p1_box <- ggplot(all_data_long |> filter(variable == "efficiency")) +
  aes(x = pow_condition, y = value) +
  geom_boxplot(aes(fill = percents)) +
  theme_classic2() +
  scale_fill_manual(
    name = "PFA Target",
    values=c(
      "0%"  = "#E69F00",  # orange
      "10%" = "#56B4E9",  # bleu
      "20%" = "#009E73",  # vert
      "30%" = "#6A3D9A"   # violet
    ))+
  
  scale_x_discrete(
    labels = c(
      "1p5" = "1.5 W/kg",
      "2p5" = "2.5 W/kg"
    )
  )+theme_classic(base_size = 8) +
  
  theme(
    legend.position = "top",
    legend.margin = margin(
      t = 0,
      r = 0,
      b = 0,
      l = -2,
      unit = "mm"
    ),
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    )
  )+
  labs(
    x = "Average MPO",
    y = " Net Efficiency (%)"
  )

p1_box

# FE

p2_box <- ggplot(all_data_long |> filter(variable == "FE")) +
  aes(x = pow_condition, y = value) +
  geom_boxplot(aes(fill = percents)) +
  theme_classic2() +
  scale_fill_manual(
    name = "PFA Target",
    values=c(
      "0%"  = "#E69F00",  # orange
      "10%" = "#56B4E9",  # bleu
      "20%" = "#009E73",  # vert
      "30%" = "#6A3D9A"   # violet
    ))+
  
  scale_x_discrete(
    labels = c(
      "1p5" = "1.5 W/kg",
      "2p5" = "2.5 W/kg"
    )
  )+
  theme_classic(base_size = 8) +
  
  theme(
    legend.position = "top",
    legend.margin = margin(
      t = 0,
      r = 0,
      b = 0,
      l = -2,
      unit = "mm"
    ),
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    )
  )+
  labs(
    x = "Average MPO",
    y = " FE (%)"
  )
p2_box


ggsave("efficiency_box_final.png", plot = p1_box, width = 84, height = 84, units="mm",dpi = 300)
ggsave("FE_box_final.png", plot = p2_box, width = 84, height = 84, units="mm",dpi = 300)
```

# Supplementary materials — Power output asymmetry (SI_pow)

```{r suppl_SI_pow_stats}

# LMM efficiency

mod_eff_pow<- lmer(efficiency ~ SI_pow+pow_condition + (1|subject), data = all_data)
summary(mod_eff_pow) 


# LMM FE
mod_FE_pow<- lmer(FE ~ SI_pow+pow_condition + (1|subject), data = all_data)
summary(mod_FE_pow) 


# LMM ready to plot efficiency

pred_eff_pow <- ggpredict(mod_eff_pow,terms = c("SI_pow", "pow_condition"))
pred_eff_pow$variable <- "efficiency"

pred_eff_pow <- pred_eff_pow |> 
  rename(pow_condition = group)

# LMM ready to plot FE

pred_FE_pow <- ggpredict(mod_FE_pow, terms = c("SI_pow", "pow_condition"))
pred_FE_pow$variable  <- "FE"

pred_FE_pow <- pred_FE_pow |> 
  rename(pow_condition = group)

```

## Graphs — Scatter plots (SI_pow)

```{r suppl_SI_pow_graphs}


p3_pow <- ggplot(all_data_long |> filter(variable == "efficiency")) +
  aes(x = SI_pow, y = value) +
  
  geom_point(
    aes(
      color = percents,
      shape = pow_condition,
      size = pow_condition
    )
  ) +
  
  geom_line(
    data = pred_eff_pow,
    aes(
      x = x,
      y = predicted,
      linetype = pow_condition
    ),
    color = "black",
    linewidth = 0.9
  ) +
  
  scale_color_manual(
    name = "PFA Target",
    values = c(
      "0%"  = "#E69F00",
      "10%" = "#56B4E9",
      "20%" = "#009E73",
      "30%" = "#6A3D9A"
    )
  ) +
  
  scale_shape_manual(
    name = "Average MPO",
    values = c(
      "1p5" = 16,
      "2p5" = 18
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  scale_size_manual(
    values = c(
      "1p5" = 2.2,
      "2p5" = 3
    )
  ) +
  
  scale_linetype_manual(
    name = "Average MPO",
    values = c(
      "1p5" = "solid",
      "2p5" = "dotdash"
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  guides(
    color = guide_legend(
      nrow = 2,
      byrow = TRUE,
      override.aes = list(size = 3)
    ),
    
    shape = guide_legend(
      nrow = 1,
      override.aes = list(size = c(2.5, 3))
    ),
    
    size = "none"
  ) +
  
  scale_x_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  labs(
    x = "MPO asymmetry (%)",
    y = "Net efficiency (%)"
  ) +
  
  theme_classic(base_size = 8) +
  
  theme(
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    ),
    
    legend.position = "top",
    legend.box = "vertical",
    
    legend.spacing.y = unit(0, "mm"),
    legend.spacing.x = unit(1, "mm"),
    
    legend.key.width = unit(8, "mm"),
    legend.key.height = unit(4, "mm"),
    
    plot.margin = margin(
      1, 1, 1, 1,
      unit = "mm"
    )
  )

p3_pow



p4_pow <- ggplot(all_data_long |> filter(variable == "FE")) +
  aes(x = SI_pow, y = value) +
  
  geom_point(
    aes(
      color = percents,
      shape = pow_condition,
      size = pow_condition
    )
  ) +
  
  geom_line(
    data = pred_FE_pow,
    aes(
      x = x,
      y = predicted,
      linetype = pow_condition
    ),
    color = "black",
    linewidth = 0.9
  ) +
  
  scale_color_manual(
    name = "PFA Target",
    values = c(
      "0%"  = "#E69F00",
      "10%" = "#56B4E9",
      "20%" = "#009E73",
      "30%" = "#6A3D9A"
    )
  ) +
  
  scale_shape_manual(
    name = "Average MPO",
    values = c(
      "1p5" = 16,
      "2p5" = 18
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  scale_size_manual(
    values = c(
      "1p5" = 2.2,
      "2p5" = 3
    )
  ) +
  
  scale_linetype_manual(
    name = "Average MPO",
    values = c(
      "1p5" = "solid",
      "2p5" = "dotdash"
    ),
    labels = c(
      "1.5 W/kg",
      "2.5 W/kg"
    )
  ) +
  
  guides(
    color = guide_legend(
      nrow = 2,
      byrow = TRUE,
      override.aes = list(size = 3)
    ),
    
    shape = guide_legend(
      nrow = 1,
      override.aes = list(size = c(2.5, 3))
    ),
    
    size = "none"
  ) +
  
  scale_x_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  scale_y_continuous(
    expand = expansion(mult = 0.02)
  ) +
  
  labs(
    x = "MPO asymmetry (%)",
    y = "FE (%)"
  ) +
  
  theme_classic(base_size = 8) +
  
  theme(
    aspect.ratio = 1,
    
    axis.title = element_text(
      face = "bold",
      size = 10
    ),
    
    axis.text = element_text(
      size = 9
    ),
    
    legend.title = element_text(
      face = "bold",
      size = 10
    ),
    
    legend.text = element_text(
      size = 9
    ),
    
    legend.position = "top",
    legend.box = "vertical",
    
    legend.spacing.y = unit(0, "mm"),
    legend.spacing.x = unit(1, "mm"),
    
    legend.key.width = unit(8, "mm"),
    legend.key.height = unit(4, "mm"),
    
    plot.margin = margin(
      1, 1, 1, 1,
      unit = "mm"
    )
  )


p4_pow

ggsave("efficiency_pow_final.png", plot = p1_box, width = 84, height = 84, units="mm",dpi = 300)
ggsave("FE_pow_final.png", plot = p2_box, width = 84, height = 84, units="mm",dpi = 300)
```

# Appendix — Model diagnostics

```{r appendix}

# This chunck is to check that the hypothesis of the statistical model are respected


diagnostic_lmm <- function(model, group = "subject") {
  
  # Linearity check
  cat("=== Linearity check ===\n")
  plot(model)
  
  # Residuals QQ-plot
  cat("=== Residuals QQ-plot ===\n")
  qqnorm(resid(model))
  qqline(resid(model))
  
  # Residuals histogram
  cat("=== Residuals histogram ===\n")
  hist(resid(model),
       main = "Histogram of Residuals",
       xlab = "Residuals")
  
  # Influence diagnostics
  cat("=== Group influence diagnostics ===\n")
  infl <- influence(model, group = group)
  plot(infl)
  
  cat("=== Cook's distances ===\n")
  print(cooks.distance(infl))
  
  # Random effects
  cat("=== Random effects ===\n")
  print(ranef(model))
  
  invisible(list(
    influence = infl,
    cooks_distance = cooks.distance(infl),
    random_effects = ranef(model)
  ))
}


diagnostic_lmm(mod_eff1)
diagnostic_lmm(mod_FE1)
diagnostic_lmm(mod_eff_pow)
diagnostic_lmm(mod_FE_pow)
```
